services:
  postgres:
    image: postgres:17
    container_name: sales-management-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "5433:5432"
    volumes:
        - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
